### PR TITLE
Added on/off text to toggle switch.

### PR DESCRIPTION
**Pull request by mpisacic**

### CODE REVIEW

**Comment by mpisacic** [comment]
Yes it can, but only problem is lack of space for text in current implementation.

**Comment by hbagarich** [comment]
aha, ok. lets try it then without additional properties

**Comment by hbagarich** [comment]
additionally, can this component now function in two modes? one with text, one without?

**Comment by mpisacic** [comment]
Fixed, if props onText and offText are passed to component component will show it, if nothing is passed on then no text will be rendered.

**Pull request merged**
